name: Build TIPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip Archive
        run: |
          unzip -o *.zip

      - name: Build
        run: |
          PROJ=$(find . -maxdepth 2 -name "*.xcodeproj" | head -n 1)
          SCHEME=$(xcodebuild -list -project "$PROJ" | awk '/Schemes:/{flag=1; next} /^$/{flag=0} flag' | head -n 1 | xargs)
          
          xcodebuild clean build \
            -project "$PROJ" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            ENTITLEMENTS_REQUIRED=NO

      - name: Package
        run: |
          mkdir Payload
          mv build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r app.tipa Payload/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: app-tipa
          path: app.tipa
